server_checker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('servers.urls', namespace='servers')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

servers/urls.py
from django.urls import path

import servers.views as vws

app_name = 'servers'

urlpatterns = [
    path('', vws.index, name='index'),
    path('server/', vws.add_server, name='server'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import users.views as vws

app_name = 'users'

urlpatterns = [
    # profile stuff
    path('profile/', vws.profile, name='profile'),
    path('profile/edit/', vws.edit_profile, name='edit_profile'),

    # auth stuff
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('signup/', vws.signup, name='signup')
]

templates/includes/footer.html
<footer>
    <div class="footer">
        &copy АО БСКБ "Нефтехимавтоматика" &bull; Адрес: 450075, РФ, Республика Башкортостан, г. Уфа, Проспект
        Октября, 149, {% now 'Y' %}
    </div>
</footer>

templates/includes/header.html
{% load static %}

<div class="header">
    <div class="header__header">
        <a href="{% url 'servers:index' %}">
            <img class="logo" src="{% static 'img/header_logo.png' %}" alt="logo">
        </a>
        {% if user.is_authenticated %}
            <a class="logout_btn" href="{% url 'users:logout' %}"> Выйти </a>
        {% endif %}
    </div>
    {% if user.is_authenticated %}
        <div class="header__body">
            <a class="main_page__link header__btn" href={% url 'servers:index' %}> Главная </a>
            <div class="profile">
                <a class="profile__link header__btn" href={% url 'users:profile' %}> Личный кабинет </a>
                <div class="profile__name"> Добро пожаловать, {{ user.username }}</div>
            </div>
        </div>
    {% endif %}
</div>

templates/includes/table.html
{% load static %}

<table class="table__content" align="center">
    <tr class="table__row table__headers">
        <th class="table__header"> IP адрес </th>
        <th class="table__header"> Имя сервера </th>
        <th class="table__header"> Статус </th>
    </tr>
    {% for row in context.servers %}
        <tr class="table__row">
         <td class="table__cell"> {{ row.ip }} </td>
         <td class="table__cell"> {{ row.name }} </td>
         <td class="table__cell"> {{ row.status }} </td>
        </tr>
    {% endfor %}
</table>