server_checker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('servers.urls', namespace='servers')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

servers/urls.py
from django.urls import path

import servers.views as vws

app_name = 'servers'

urlpatterns = [
    path('', vws.index, name='index'),
    path('server/', vws.add_server, name='server'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import users.views as vws

app_name = 'users'

urlpatterns = [
    # profile stuff
    path('profile/', vws.profile, name='profile'),
    path('profile/edit/', vws.edit_profile, name='edit_profile'),

    # auth stuff
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('signup/', vws.signup, name='signup')
]

templates/add_server_page.html
{% extends 'base.html' %}
{% block title %} Добавление сервера {% endblock %}

{% block content %}
        <div class="table__form">
            <div class="table__add_server__label"> Добавить сервер </div>
            <div class="table__add_server">
                <form action="" method="post">
                    {% csrf_token %}
                    <label class="server_form__label" for="{{ form.ip.id_for_label }}"> IP </label>
                    {{ form.ip }}<br>
                    <label class="server_form__label" for="{{ form.name.id_for_label }}"> name </label>
                    {{ form.name }}<br>
                    <input class="server_form__input" type="submit" value="Отправить">
                </form>
            </div>
        </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %} Главная {% endblock %} | БСКБ
    </title>

    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    {% include 'includes/header.html' %}
    <main>
        <div class="container">
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'includes/footer.html'%}
</body>
</html>

templates/edit_profile.html
{% extends 'base.html' %}

{% block title %} Изменение данных личного кабинета {% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="OK">
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="index__label">
        <p>Мониторинг состояния серверов</p>
        {% if user.is_superuser %}
            <a class="add_server__link" href="{% url 'servers:server' %}"> Добавить сервер </a>
        {% endif %}
    </div>


    {% include 'includes/table.html' %}
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block title %} Личный кабинет {% endblock %}

{% block content %}
    <div class="profile__page">
        <div class="profile__item">
            <div class="item__label">Фамилия:</div>
            <div class="item__content">{{ user.last_name }}</div>
        </div>
        <div class="profile__item">
            <div class="item__label">Имя:</div>
            <div class="item__content">{{ user.first_name }}</div>
        </div>
        <div class="profile__item">
            <div class="item__label">Отчество:</div>
            <div class="item__content">{{ user.middle_name }}</div>
        </div>

        <div class="profile__item">
            <div class="item__label">Должность:</div>
            <div class="item__content">{{ user.work_position }}</div>
        </div>

        <div class="profile__item">
            <div class="item__label">Почта:</div>
            <div class="item__content">{{ user.email }}</div>
        </div>

        <a class="profile__edit_link" href="{% url 'users:edit_profile' %}"> Изменить данные </a>
    </div>

{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% block title %} Регистрация {% endblock %}

{% block content %}
    <div>Регистрация</div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="OK">
    </form>
{% endblock %}